INSERT INTO users (userName,point,isActive) VALUES ('user1','0','false');
INSERT INTO users (userName,point,isActive) VALUES ('user2','0','false');
INSERT INTO users (userName,point,isActive) VALUES ('user3','0','false');
INSERT INTO users (userName,point,isActive) VALUES ('user4','0','false');
INSERT INTO users (userName,point,isActive) VALUES ('admin',NULL,'false');

INSERT INTO quizzes (question,isActive) VALUES ('日本の和食文化の一環として知られる「三大うどん」に含まれるうどんはどれ？','true');
INSERT INTO quizzes (question,isActive) VALUES ('日本の「国花」とされるのはどの花？','true');
INSERT INTO quizzes (question,isActive) VALUES ('日本で最も多くの人が利用している鉄道駅はどこ？','true');
INSERT INTO quizzes (question,isActive) VALUES ('日本で使われる年号（元号）のシステムは、何時代に始まったものでしょう？','true');
INSERT INTO quizzes (question,isActive) VALUES ('2024年の日本での学生向け入試改革として、新たに設けられた科目は何？','true');
INSERT INTO quizzes (question,isActive) VALUES ('日本の元号が「令和」に変わったのは西暦何年？','true');
INSERT INTO quizzes (question,isActive) VALUES ('2024年、日本で人気が再燃した「昭和レトロ」ブームの一環として注目されているものは？','true');
INSERT INTO quizzes (question,isActive) VALUES ('「富士山」がある都道府県はどれでしょう？','true');
INSERT INTO quizzes (question,isActive) VALUES ('奈良県の「東大寺」にある大仏は、どの時代に建立されたものでしょう？','true');
INSERT INTO quizzes (question,isActive) VALUES ('日本三名園のひとつである「兼六園」があるのはどの都道府県？','true');
INSERT INTO quizzes (question,isActive) VALUES ('コオロギの耳はどこにあるでしょう?','true');
INSERT INTO quizzes (question,isActive) VALUES ('「学ラン」の「ラン」とは何でしょうか?','true');
INSERT INTO quizzes (question,isActive) VALUES ('自衛隊は毎週金曜日に必ずあるものを食べています。それは何でしょう?','true');
INSERT INTO quizzes (question,isActive) VALUES ('視力検査に使われるアルファベットの「C」のような形はどこの国で生まれたでしょうか?','true');
INSERT INTO quizzes (question,isActive) VALUES ('「リーチ」の語源となったものはどれでしょうか?','true');
INSERT INTO quizzes (question,isActive) VALUES ('海上で事件や事故が起こった時、海上保安庁に通報する番号はどれでしょうか？','true');
INSERT INTO quizzes (question,isActive) VALUES ('お寿司屋さんでは、醤油のことをある色の名前で呼びます。何と呼ぶでしょうか？','true');
INSERT INTO quizzes (question,isActive) VALUES ('公衆電話に一度に入れることができる硬貨の枚数は何枚でしょうか？','true');
INSERT INTO quizzes (question,isActive) VALUES ('ムカデが苦手としている匂いはどれでしょうか？','true');
INSERT INTO quizzes (question,isActive) VALUES ('ガリガリ君の当たりの確率はどれくらい?','true');



INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('讃岐うどん、博多うどん、きしめん','伊勢うどん、稲庭うどん、讃岐うどん','五島うどん、稲庭うどん、月見うどん','水沢うどん、伊勢うどん、博多うどん','2');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('桜','梅','菊','百合','1');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('新宿駅','東京駅','渋谷駅','大阪駅','1');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('奈良時代','平安時代','飛鳥時代','鎌倉時代','3');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('デジタルリテラシー','グローバルスタディーズ','コミュニケーションスキル','健康管理学','1');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('2017年','2018年','2019年','2020年','3');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('銀幕の映画','縁日スタイルのイベント','レトロゲーム','盆踊り大会','3');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('長野県と新潟県','山梨県と静岡県','静岡県と愛知県','山梨県と岐阜県','2');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('飛鳥時代','奈良時代','平安時代','鎌倉時代','2');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('東京都','石川県','京都府','広島県','2');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('顔の横','頭頂部','お尻','足','4');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('花のラン','オランダ','ランダム','ランキング','2');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('クリームシチュー','ハヤシライス','カレー','ハッシュドビーフ','3');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('日本','アメリカ','イタリア','フランス','4');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('パチンコ','麻雀','ポーカー','将棋','2');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('104','118','177','189','2');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('アカ','ミドリ','ムラサキ','クロ','3');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('10円玉2枚と100円玉1枚','10円玉5枚と100円玉4枚','0円玉10枚と100円玉8枚','枚数制限は無い','2');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('牛乳','人間のオナラ','かつおぶし','ハッカ','4');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('1%','2%','3%','4%','3');
