INSERT INTO users (userName,point,isActive,rank) VALUES ('user1','0','false','0');
INSERT INTO users (userName,point,isActive,rank) VALUES ('user2','0','false','0');
INSERT INTO users (userName,point,isActive,rank) VALUES ('user3','0','false','0');
INSERT INTO users (userName,point,isActive,rank) VALUES ('user4','0','false','0');
INSERT INTO users (userName,point,isActive,rank) VALUES ('admin',NULL,'false',NULL);

INSERT INTO quizzes (question) VALUES ('日本の和食文化の一環として知られる「三大うどん」に含まれるうどんはどれ？');
INSERT INTO quizzes (question) VALUES ('日本の「国花」とされるのはどの花？');
INSERT INTO quizzes (question) VALUES ('日本で最も多くの人が利用している鉄道駅はどこ？');
INSERT INTO quizzes (question) VALUES ('日本で使われる年号（元号）のシステムは、何時代に始まったものでしょう？');
INSERT INTO quizzes (question) VALUES ('2024年の日本での学生向け入試改革として、新たに設けられた科目は何？');
INSERT INTO quizzes (question) VALUES ('日本の元号が「令和」に変わったのは西暦何年？');
INSERT INTO quizzes (question) VALUES ('2024年、日本で人気が再燃した「昭和レトロ」ブームの一環として注目されているものは？');
INSERT INTO quizzes (question) VALUES ('「富士山」がある都道府県はどれでしょう？');
INSERT INTO quizzes (question) VALUES ('奈良県の「東大寺」にある大仏は、どの時代に建立されたものでしょう？');
INSERT INTO quizzes (question) VALUES ('日本三名園のひとつである「兼六園」があるのはどの都道府県？');
INSERT INTO quizzes (question) VALUES ('コオロギの耳はどこにあるでしょう?');
INSERT INTO quizzes (question) VALUES ('「学ラン」の「ラン」とは何でしょうか?');
INSERT INTO quizzes (question) VALUES ('自衛隊は毎週金曜日に必ずあるものを食べています。それは何でしょう?');
INSERT INTO quizzes (question) VALUES ('視力検査に使われるアルファベットの「C」のような形はどこの国で生まれたでしょうか?');
INSERT INTO quizzes (question) VALUES ('「リーチ」の語源となったものはどれでしょうか?');
INSERT INTO quizzes (question) VALUES ('海上で事件や事故が起こった時、海上保安庁に通報する番号はどれでしょうか？');
INSERT INTO quizzes (question) VALUES ('お寿司屋さんでは、醤油のことをある色の名前で呼びます。何と呼ぶでしょうか？');
INSERT INTO quizzes (question) VALUES ('公衆電話に一度に入れることができる硬貨の枚数は何枚でしょうか？');
INSERT INTO quizzes (question) VALUES ('ムカデが苦手としている匂いはどれでしょうか？');
INSERT INTO quizzes (question) VALUES ('ガリガリ君の当たりの確率はどれくらい?');
INSERT INTO quizzes (question) VALUES ('職業にも学業にも職業訓練にもついていないものを総称してNEETと呼ぶがそのNEETに含まれない単語は?');
INSERT INTO quizzes (question) VALUES ('「紅白歌合戦」の放送開始年は?');
INSERT INTO quizzes (question) VALUES ('スタジオジブリの映画で最も公開されたのが古い作品は?');
INSERT INTO quizzes (question) VALUES ('同じ意味の文を繰り返し発言することを「小泉構文」と言いますが、この「小泉」さんのフルネームは次のうちどれ?');
INSERT INTO quizzes (question) VALUES ('音MADとして有名になり、コンビニエンスストアでも宣伝が行われていた大学は?');
INSERT INTO quizzes (question) VALUES ('あるキャラクターの死に様が「サタデーナイトフィーバー」のワンシーンに酷似しておりネットミームとなったアニメのタイトルは?');
INSERT INTO quizzes (question) VALUES ('「たたら製鉄」が古くから行われていたことで有名な日本の地方はどこ？');
INSERT INTO quizzes (question) VALUES ('東京にある「国会議事堂」の建設が完成したのはいつでしょう?');
INSERT INTO quizzes (question) VALUES ('日本で「最初の元号」は何だったでしょう?');
INSERT INTO quizzes (question) VALUES ('日本の新幹線が開業したのは何年でしょうか?');
INSERT INTO quizzes (question) VALUES ('座右の銘は英語で何というでしょう？');
INSERT INTO quizzes (question) VALUES ('コアラの一日の平均睡眠時間は？');
INSERT INTO quizzes (question) VALUES ('飛行機の中で食べれるように作られた野菜はどれでしょう？');
INSERT INTO quizzes (question) VALUES ('「Google」のロゴの二つの「o」に使用されている色の組み合わせはなに？');
INSERT INTO quizzes (question) VALUES ('桜肉といえばなんの肉でしょう?');
INSERT INTO quizzes (question) VALUES ('最高視聴率を誇る国内アニメ番組は？');
INSERT INTO quizzes (question) VALUES ('卒業式ソングの定番でもあるレミオロメンの『3月9日』。元々は何のために作られた曲？');
INSERT INTO quizzes (question) VALUES ('映画『君の名は。』の音楽を担当したバンドは何？');
INSERT INTO quizzes (question) VALUES ('次のうち、メンバー全員が幼稚園からの幼なじみ、バンド結成は高校時代というグループはどれ？');
INSERT INTO quizzes (question) VALUES ('2009年の「NHK全国学校音楽コンクール」中学生の課題曲『YELL』はどのアーティストの曲？');
INSERT INTO quizzes (question) VALUES ('2008年の「NHK全国学校音楽コンクール」中学生の課題曲『手紙』はどのアーティストの曲？');
INSERT INTO quizzes (question) VALUES ('オリコン週間カラオケ・ランキングで、85週連続1位という記録を持つ曲は何？');
INSERT INTO quizzes (question) VALUES ('次のうち、「小説を音楽にするユニット」というコンセプトのユニットはどれ？');
INSERT INTO quizzes (question) VALUES ('日本での興行収入記録を持つ、宮崎駿監督の作品は何？');
INSERT INTO quizzes (question) VALUES ('「映画ドラえもん」シリーズ１作目のタイトルは何？');
INSERT INTO quizzes (question) VALUES ('大ヒットした映画『シン・ゴジラ』のキャッチコピー「現実 対 虚構」。「虚構」は「ゴジラ」と読ませますが、「現実」は何と読ませる？');
INSERT INTO quizzes (question) VALUES ('「アニメ流行語大賞2022」で銀賞を受賞した「さかなー」は何というアニメのセリフ？');
INSERT INTO quizzes (question) VALUES ('「アニメ流行語大賞2022」で金賞を受賞した「ウタ」は何というアニメのセリフ？');
INSERT INTO quizzes (question) VALUES ('アニメ「ブルーロック」で行われた青い監獄(ブルーロック)プロジェクトの三次選考は次のうちどれか？');
INSERT INTO quizzes (question) VALUES ('アニメ「ブルーロック」で行われた入寮テスト「オニごっこ」の制限時間は？');



INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('讃岐うどん、博多うどん、きしめん','伊勢うどん、稲庭うどん、讃岐うどん','五島うどん、稲庭うどん、月見うどん','水沢うどん、伊勢うどん、博多うどん','伊勢うどん、稲庭うどん、讃岐うどん');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('桜','梅','菊','百合','桜');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('新宿駅','東京駅','渋谷駅','大阪駅','新宿駅');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('奈良時代','平安時代','飛鳥時代','鎌倉時代','飛鳥時代');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('デジタルリテラシー','グローバルスタディーズ','コミュニケーションスキル','健康管理学','デジタルリテラシー');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('2017年','2018年','2019年','2020年','2019年');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('銀幕の映画','縁日スタイルのイベント','レトロゲーム','盆踊り大会','レトロゲーム');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('長野県と新潟県','山梨県と静岡県','静岡県と愛知県','山梨県と岐阜県','山梨県と静岡県');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('飛鳥時代','奈良時代','平安時代','鎌倉時代','奈良時代');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('東京都','石川県','京都府','広島県','石川県');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('顔の横','頭頂部','お尻','足','足');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('花のラン','オランダ','ランダム','ランキング','オランダ');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('クリームシチュー','ハヤシライス','カレー','ハッシュドビーフ','カレー');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('日本','アメリカ','イタリア','フランス','フランス');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('パチンコ','麻雀','ポーカー','将棋','麻雀');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('104','118','177','189','118');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('アカ','ミドリ','ムラサキ','クロ','ムラサキ');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('10円玉2枚と100円玉1枚','10円玉5枚と100円玉4枚','0円玉10枚と100円玉8枚','枚数制限は無い','10円玉5枚と100円玉4枚');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('牛乳','人間のオナラ','かつおぶし','ハッカ','ハッカ');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('1%','2%','3%','4%','3%');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('No','Employment','Education','Traning','No');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('1951年','1954年','1956年','1960年','1951年');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('天空の城ラピュタ','紅の豚','もののけ姫','風の谷のナウシカ','風の谷のナウシカ');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('小泉孝太郎','小泉純一郎','小泉進次郎','小泉今日子','小泉進次郎');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('帝京大学','帝京平成大学','慶応義塾大学','中央大学','帝京平成大学');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('機動戦士ガンダム鉄血のオルフェンズ','機動戦士ガンダムOO','機動戦士ガンダムF91','機動戦士ガンダムSEED','機動戦士ガンダム鉄血のオルフェンズ');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('四国地方','北海道地方','山陰地方','東北地方','山陰地方');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('1889年','1900年','1936年','1945年','1936年');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('慶応','大化','元和','天平','大化');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('1960年','1964年','1970年','1972年','1964年');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('アンセム','スローガン','ブーム','モットー','モットー');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('8時間','12時間','16時間','20時間','20時間');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('ミニトマト','パプリカ','アボカド','ズッキーニ','ミニトマト');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('青色と黄色','青色と緑色','赤色と黄色','赤色と緑色','赤色と黄色');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('猪','鹿','馬','鶏','馬');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('サザエさん','ドラえもん','ちびまる子ちゃん','ワンピース','ちびまる子ちゃん');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('結婚祝い','命日','七五三','快気祝い','結婚祝い');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('BUMP OF CHICKEN','RADWIMPS','King Gnu','KANA-BOON','RADWIMPS');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('レミオロメン','BUMP OF CHICKEN','SEKAI NO OWARI','ゆず','SEKAI NO OWARI');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('Superfly','いきものがかり','YUI','Little Glee Monster','いきものがかり');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('由紀さおり','back number','アンジェラ・アキ','Superfly','アンジェラ・アキ');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('ゴールデンボンバー 『女々しくて』','星野源『恋』','米津玄師『Lemon』','AKB48『ヘビーローテーション』','米津玄師『Lemon』');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('YOASOBI','優里','ヨルシカ','ずっと真夜中でいいのに。','YOASOBI');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('崖の上のポニョ','風立ちぬ','千と千尋の神隠し','ハウルの動く城','千と千尋の神隠し');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('のび太の宇宙開拓史','のび太の恐竜','のび太の大魔境','のび太の海底鬼岩城','のび太の恐竜');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('セカイ','ヒト','リアル','ニッポン','ニッポン');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('ONE PIECE FILM RED','SPY×FAMILY','リコリス・リコイル','機動戦士ガンダム 水星の魔女','リコリス・リコイル');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('リコリス・リコイル','機動戦士ガンダム 水星の魔女','ONE PIECE FILM RED','SPY×FAMILY','ONE PIECE FILM RED');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('新英雄大戦（ネオ・エゴイスト・リーグ）','奪敵決戦（ライバルリー・バトル）','総当たりグループリーグマッチ','適性試験（トライアウト）','適性試験（トライアウト）');
INSERT INTO quizOptions (choice_1,choice_2,choice_3,choice_4,correct) VALUES ('130秒','133秒','136秒','139秒','136秒');
